version: '3.8'

services:
  frontend:
    image: ${REGISTRY_NAME:-ihsan}/frontend:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "8080:80" 
    environment:
      - VITE_API_URL=/api

  backend:
    image: ${REGISTRY_NAME:-ihsan}/backend:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - /opt/ihsan/certbot/conf:/etc/letsencrypt  # Use absolute path
      - /opt/ihsan/certbot/www:/var/www/certbot   # Use absolute path
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - /opt/ihsan/certbot/conf:/etc/letsencrypt  # Use absolute path
      - /opt/ihsan/certbot/www:/var/www/certbot   # Use absolute path
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data: