version: '3.8'

services:
  nginx-certbot:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./nginx-certbot.conf:/etc/nginx/conf.d/default.conf