name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd backend
          npm ci --legacy-peer-deps || echo "Backend install failed but continuing"
          cd ../
          npm ci --legacy-peer-deps || echo "Frontend install failed but continuing"

  build-and-deploy:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Create artifacts directory first
      - name: Create artifacts directory
        run: mkdir -p ./artifacts
      
      # Build Docker images directly without export
      - name: Build backend image
        run: |
          docker build -t ihsan/backend:latest -f Dockerfile.backend .
          
      - name: Build frontend image
        run: |
          docker build -t ihsan/frontend:latest -f Dockerfile.frontend .
          
      - name: Save Docker images to files
        run: |
          docker save ihsan/backend:latest > ./artifacts/backend.tar
          docker save ihsan/frontend:latest > ./artifacts/frontend.tar
          ls -la ./artifacts/
      
      # Create required deployment files
      - name: Create deployment files
        run: |
          # Create docker-compose.prod.yml
          cat > ./artifacts/docker-compose.prod.yml << 'EOF'
          version: "3.8"

          services:
            frontend:
              image: ihsan/frontend:latest
              restart: always
              ports:
                - "8080:80"
              environment:
                - VITE_API_URL=/api

            backend:
              image: ihsan/backend:latest
              restart: always
              ports:
                - "3000:3000"
              environment:
                - NODE_ENV=production
                - JWT_SECRET=${JWT_SECRET}
                - DB_HOST=${DB_HOST:-postgres}
                - DB_PORT=${DB_PORT:-5432}
                - DB_USERNAME=${DB_USERNAME}
                - DB_PASSWORD=${DB_PASSWORD}
                - DB_DATABASE=${DB_DATABASE}
              depends_on:
                - postgres

            postgres:
              image: postgres:15-alpine
              restart: always
              volumes:
                - postgres_data:/var/lib/postgresql/data
              environment:
                - POSTGRES_PASSWORD=${DB_PASSWORD}
                - POSTGRES_USER=${DB_USERNAME}
                - POSTGRES_DB=${DB_DATABASE}
              ports:
                - "5432:5432"

            nginx:
              image: nginx:alpine
              restart: always
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
              depends_on:
                - frontend
                - backend

          volumes:
            postgres_data:
          EOF

          # Create nginx-prod.conf
          cat > ./artifacts/nginx-prod.conf << 'EOF'
          server {
              listen 80;
              
              location / {
                  proxy_pass http://frontend:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
              
              location /api/ {
                  proxy_pass http://backend:3000/api/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
          EOF

          # Create .env.production
          cat > ./artifacts/.env.production << EOF
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_HOST=postgres
          DB_PORT=5432
          EOF

          ls -la ./artifacts/
      
      - name: Upload deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "./artifacts/*"
          target: "/opt/ihsan"
          strip_components: 1
      
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Check Docker installation
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              # Update package lists
              sudo apt-get update
              
              # Install requirements
              sudo apt-get install -y \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg \
                lsb-release
                
              # Add Docker's official GPG key
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              
              # Set up Docker repository
              echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              
              # Install Docker
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              
              # Add current user to docker group
              sudo usermod -aG docker $USER
              
              # Notify
              echo "Docker installed successfully"
            fi
            
            # Check Docker Compose installation
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              echo "Docker Compose installed successfully"
            fi
            
            # Create directory if it doesn't exist
            mkdir -p /opt/ihsan
            
            # Navigate to app directory
            cd /opt/ihsan
            
            # Load Docker images
            echo "Loading Docker images..."
            docker load < backend.tar || echo "Failed to load backend image"
            docker load < frontend.tar || echo "Failed to load frontend image"
            
            # Stop existing containers
            docker-compose -f docker-compose.prod.yml down || echo "No previous containers to stop"
            
            # Start new containers
            echo "Starting containers..."
            docker-compose -f docker-compose.prod.yml up -d
            
            # Clean up tar files (optional)
            rm -f backend.tar frontend.tar
